---
- name: install {{ service }}
  yum:
    name: "{{ service }}"
    state: latest

- name: enable {{ service }}
  service:
    name: "{{ service }}"
    enabled: yes

- name: configure {{ service }}
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: "{{ mode }}"

- name: restart {{ service }}
  service:
    name: "{{ service }}"
    state: restarted
