---
- name: install postgres
  yum:
    name: postgresql-server
    state: latest

- name: enable postgres
  service:
    name: postgresql
    enabled: yes

- name: initilize postgres
  run_once: true
  command: "{{item}}" 
  with_items: 
    - postgresql-setup initdb
    - chkconfig postgresql on

- name: start postgres
  service:
    name: postgresql.service
    state: started



#How to make the above itempotent?
#Relates to what we are doing with server deployment
#Can we do this?
