---
# Bad ansible! This playbook is an example of poor/bad practices!
# Bad practices may include:
#
#   Poor formatting and structure
#   Poor use of YAML - but good enough to parse
#   Inconsistent style
#   Incorrect use of modules
#   Poor module choice
#   Unclear names
#   Hard coding / poor use of variables
#   Roles - what are roles?
#   Bare variables
#   No use of handlers

- hosts: jumpbox
  gather_facts: true
  roles:
  - name: osp-facts


- name: configuration
  hosts: frontends, apps, appdbs
  gather_facts: false
  become: true

  tasks:
  - name: enable repos
    template:
      src: ./open_three-tier-app.repo #need to hide this in ansible vault
      dest: /etc/yum.repos.d/open_three-tier-app.repo
      mode: 0644


- name: setup lb
  hosts: frontends
  gather_facts: false
  become: true
  roles:
    - {role: loadbalancer-tier, tags: lb}


- name: setup apps
  hosts: apps
  gather_facts: false
  become: true
  roles:
    - {role: application-tier, tags: apps}



- name: setup db
  hosts: appdbs
  gather_facts: true #must be set to true for postgresql role to work
  become: true
  roles:
    - {role: geerlingguy.postgresql, tags: db}


  #remember to remove the files in pgsql directory on appdb1 sudo vim /var/lib/pgsql/data/pg_hba.conf

