---
- name: install tomcat
  yum:
    name: tomcat
    state: latest

- name: enable tomcat
  service:
    name: tomcat
    enabled: yes

- name: create Ansible tomcat directory
  file:
    path: "{{ tomcat_dir }}"
    state: directory

- name: copy static index.html to tomcat webapps/ROOT/index.html
  template:
    src: index.html.j2
    dest: "{{ tomcat_dir }}/index.html"
    mode: "{{ tomcat_mode }}"

- name: restart tomcat
  service:
    name: tomcat
    state: restarted
