---
- name: install {{ service }}
  yum:
    name: "{{ service }}"
    state: latest

- name: enable {{ service }}
  service:
    name: "{{ service }}"
    enabled: yes

- name: create root {{ service }} directory
  file:
    path: "{{ dir }}"
    state: directory

- name: copy static index.html to tomcat {{ dir }}
  template:
    src: index.html.j2
    dest: "{{ dir }}/index.html"
    mode: "{{ mode }}"

- name: restart {{ service }}
  service:
    name: "{{ service }}"
    state: restarted
